# -*- coding: utf-8 -*-
"""Deep Q-Learning for Lunar Landing - Partial Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pTz6So8t2tc04roc5l1w6ONm67uoxBEF

# Deep Q-Learning for Lunar Landing

## Part 0 - Installing the required packages and importing the libraries

### Installing Gymnasium
"""

!pip install gymnasium
!pip install "gymnasium[atari, accept-rom-license]"
!apt-get install -y swig
!pip install gymnasium[box2d]

"""### Importing the libraries"""

import os
import random
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import torch.autograd as autograd
from torch.autograd import Variable
from collections import deque, namedtuple

"""## Part 1 - Building the AI

### Creating the architecture of the Neural Network
"""

class Network(nn.Module):

  def __init__(self, state_size, action_size, seed = 42) -> None:
    # activate inheritance
    super(Network, self).__init__()
    # activate seed
    self.seed = torch.manual_seed(seed)

    #architecture
    self.fc1 = nn.Linear(state_size, 64)  # 64 is number of fully connected
                                          # neurons on the first layer. 64
                                          # was reached after experimentation
    self.fc2 = nn.Linear(64, 64) # 2 layers!
    self.fc3 = nn.Linear(64, action_size) # output layer
    #

  def forward(self, state):
    x = self.fc1(state)
    x = F.relu(x)  # F is torch.nn.functional
                   # relu() rectifier activation function
    x = self.fc2(x)
    x = F.relu(x)
    return self.fc3(x)

"""## Part 2 - Training the AI

### Setting up the environment
"""

import gymnasium as gym
env = gym.make('LunarLander-v2')
state_shape    = env.observation_space.shape
state_size     = env.observation_space.shape[0]
number_actions = env.action_space.n
print('State shape: ', state_shape)
print('State size: ', state_size)
print('Number of actions: ', number_actions)

"""### Initializing the hyperparameters"""

learning_rate           = 5e-4  # best value after experimentation
minibatch_size          = 100
discount_factor         = 0.99 # aka gamma
replay_buffer_size      = int(1e5) # the size of the memory of the AI (experiences in the memory of the agent)
interpolation_parameter = 1e-3 # aka tau

"""### Implementing Experience Replay"""

class ReplayMemory(object):

  def __init__(self, capacity):
    self.device   = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    self.capacity = capacity
    self.memory   = []

  def push(self, event):
    self.memory.append(event)
    if len(self.memory) > self.capacity: # removing the oldest event
      del self.memory[0]

  def sample(self, batch_size):
    experiences = random.sample(self.memory, k = batch_size)
    states = torch.from_numpy(np.vstack([e[0] for e in experiences if e is not None])).float().to(self.device)
    actions = torch.from_numpy(np.vstack([e[1] for e in experiences if e is not None])).long().to(self.device)
    rewards = torch.from_numpy(np.vstack([e[2] for e in experiences if e is not None])).float().to(self.device)
    next_states = torch.from_numpy(np.vstack([e[3] for e in experiences if e is not None])).float().to(self.device)
    dones = torch.from_numpy(np.vstack([e[4] for e in experiences if e is not None]).astype(np.uint8)).float().to(self.device)
    return states, next_states, actions, rewards, dones

"""### Implementing the DQN class"""

class Agent():

  def __init__(self, state_size, action_size):
    self.device   = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    self.state_size = state_size
    self.action_size = action_size
    # local_qnetwork is the Q network that will select the actions
    # target_qnetwork is the Q network that will calculate the target Q-values that
    #    will be used in the training of the local_qnetwork
    # dual q network used to stabilize the learning process
    self.local_qnetwork = Network(state_size, action_size).to(self.device)
    self.target_qnetwork = Network(state_size, action_size).to(self.device)
    self.optimizer = optim.Adam(self.local_qnetwork.parameters(), lr = learning_rate)
    self.memory = ReplayMemory(replay_buffer_size)
    self.t_step = 0

  def step(self, state, action, reward, next_state, done):
    self.memory.push((state, action, reward, next_state, done))
    self.t_step = (self.t_step + 1) % 4 # learning only every 4 steps
    if self.t_step == 0:
      if len(self.memory.memory) > minibatch_size:
        experiences = self.memory.sample(minibatch_size)
        self.learn(experiences, discount_factor)

  def act(self, state, epsilon = 0.):
    # adding extra dimension (to accommodate for the batch ID)
    state = torch.from_numpy(state).float().unsqueeze(0).to(self.device)
    self.local_qnetwork.eval() # evaluation mode
    with torch.no_grad(): # check gradient computation disabled (we are in inference)
      action_values = self.local_qnetwork(state)
    self.local_qnetwork.train() # set back to training mode
    if random.random() > epsilon:
      # select the action with the highest Q value
      return np.argmax(action_values.cpu().data.numpy())
    else: # select at random
      return random.choice(np.arange(self.action_size))

  def learn(self, experiences, discount_factor):
    states, next_states, actions, rewards, dones = experiences
    # forward propagate the next states for our target qnetwork
    # we want to take the maximum of the action values
    # We have to detach the action values of the tensor. The resulting tensor is detached from
    #   the computation graph. We won't be tracking gradients for this tensor during the backward prop.
    next_q_targets = self.target_qnetwork(next_states).detach().max(1)[0].unsqueeze(1) #max along dim 1. dim for batch is now 1.
    q_targets = rewards + (discount_factor * next_q_targets * (1 - dones))
    q_expected = self.local_qnetwork(states).gather(1, actions)
    loss = F.mse_loss(q_expected, q_targets)
    self.optimizer.zero_grad()
    loss.backward()
    self.optimizer.step()
    self.soft_update(self.local_qnetwork, self.target_qnetwork, interpolation_parameter)

  def soft_update(self, local_model, target_model, interpolation_parameter):
    # soft update is used to update target q network params by blending them with the local q network params
    #   this is needed to prevent abrupt changes which could destabilize the training
    for target_param, local_param in zip(target_model.parameters(), local_model.parameters()):
      target_param.data.copy_(interpolation_parameter * local_param.data  + (1.0 - interpolation_parameter) * target_param)

"""### Initializing the DQN agent"""

agent = Agent(state_size, number_actions)

"""### Training the DQN agent"""

number_episodes = 2000 # max num episodes over which we want to train our agent
maximum_number_timesteps_per_episode = 1000
epsilon_starting_value = 1.0
epsilon_ending_value = 0.01  # we decay epsilon over time
epsilon_decay_value = 0.995
epsilon = epsilon_starting_value
scores_on_100_episodes = deque(maxlen = 100)

for episode in range(1, number_episodes + 1):
  # reset state
  state, _ = env.reset()  # env is where the 'real' action takes place
  # init the score
  score = 0
  for t in range(maximum_number_timesteps_per_episode): # learning loop
    # action selected
    action = agent.act(state, epsilon)
    # we make a move, we are in a new state
    next_state, reward, done, _, _ = env.step(action)  # done is a bool: are we done with this episode?
    # We use the step method, that includes the learn method
    agent.step(state, action, reward, next_state, done) # backpropagation
    #
    state = next_state
    score += reward
    if done:
      break
  # episode finished
  scores_on_100_episodes.append(score)
  epsilon = max(epsilon_ending_value, epsilon_decay_value * epsilon)
  # advanced print
  # \r: start to the beg of the line when printing (so we remove previous print)
  # end = "": no new line after printing
  print('\rEpisode {}\tAverage Score: {:.2f}'.format(episode, np.mean(scores_on_100_episodes)), end = "")
  if episode % 100 == 0:
    print('\rEpisode {}\tAverage Score: {:.2f}'.format(episode, np.mean(scores_on_100_episodes)))
  if np.mean(scores_on_100_episodes) >= 200.0: # condition to win
    # note sure I understand the '-100'
    print('\nEnvironment solved in {:d} episodes!\tAverage Score: {:.2f}'.format(episode - 100, np.mean(scores_on_100_episodes)))
    torch.save(agent.local_qnetwork.state_dict(), 'checkpoint.pth') # saving the solved one!
    break

"""## Part 3 - Visualizing the results"""

import glob
import io
import base64
import imageio
from IPython.display import HTML, display
from gym.wrappers.monitoring.video_recorder import VideoRecorder

def show_video_of_model(agent, env_name):
    env = gym.make(env_name, render_mode='rgb_array')
    state, _ = env.reset()
    done = False
    frames = []
    while not done:
        frame = env.render()
        frames.append(frame)
        action = agent.act(state)
        state, reward, done, _, _ = env.step(action.item())
    env.close()
    imageio.mimsave('video.mp4', frames, fps=30)

show_video_of_model(agent, 'LunarLander-v2')

def show_video():
    mp4list = glob.glob('*.mp4')
    if len(mp4list) > 0:
        mp4 = mp4list[0]
        video = io.open(mp4, 'r+b').read()
        encoded = base64.b64encode(video)
        display(HTML(data='''<video alt="test" autoplay
                loop controls style="height: 400px;">
                <source src="data:video/mp4;base64,{0}" type="video/mp4" />
             </video>'''.format(encoded.decode('ascii'))))
    else:
        print("Could not find video")

show_video()